### ISSUE TITLE
Releases not distributed anymore

### ISSUE THREAD

**Issue by sdebruyn** [cake-contrib/Cake.AppCenter#10]
Looks like App Center changed something yesterday. All of our projects started having failed builds. The builds fail with the following error message:

```
AppCenter: Process returned an error (exit code 3).
```

When I look in App Center, the app is uploaded but it hasn't been distributed to any distribution group.

We are building on Bitrise macOS Visual Studio stable hosts.

**Comment by gep13** [comment]
@MihaMarkic can you offer any help here?

**Comment by MihaMarkic** [comment]
@SamuelDebruyn @gep13 I have to do a distribution later on today, will let you know.

**Comment by sdebruyn** [comment]
Looks like it's an issue on App Center's end. It was resolved a few minutes ago.

**Comment by MihaMarkic** [comment]
@gep13 @SamuelDebruyn  Worked here as well. Thanks for the feedback.
