### ISSUE TITLE
ArgumentCustomization is ignored on Settings for Aliases

### ISSUE THREAD

**Issue by Cheesebaron** [cake-contrib/Cake.AppCenter#11]
If you for instance create an instance of `AppCenterTestRunUitestSettings` and use the `ArgumentCustomization` property from the inherited Cake `ToolSettings`. This property and customization of arguments is ignored in the resulting command.

## Expected Behavior
```csharp
var settings = new AppCenterTestRunUitestSettings
{
    ...
    ArgumentCustomization = args => args.Append("--debug")
};
```

I would expect this to add `--debug` at the end of the command run.

## Current Behavior
ArgumentCustomization prop is entirely ignored

## Possible Solution
Make `ArgumentsBuilderExtension` aware of the `ArgumentCustomization` prop.

**Comment by MihaMarkic** [comment]
Hey @Cheesebaron 
You sure about this? I made a simple test like 

```csharp
var settings = new AppCenterTestRunUitestSettings
 {
       ArgumentCustomization = args => args.Append("--debug")
};
AppCenterTestRunUitest(settings);
```
and when I invoke the script like
`.\build.ps1 -Target TestRunUitest -Verbosity Diagnostic`

I see the following output:
`Executing: "C:/Program Files/nodejs/appcenter.cmd" test run uitest --debug`

**Comment by Cheesebaron** [comment]
Actually, I think I got fooled by the output that the tool provides. Running Cake with diagnostics output, did show that it wasn't ignored. I think we can close this 👍
