### ISSUE TITLE
API docs generated are all in the same General category

### ISSUE THREAD

**Issue by Cheesebaron** [cake-contrib/Cake.AppCenter#12]
When you look at the AppCenter reference here: https://cakebuild.net/dsl/appcenter/

All methods are listed under the same category. Makes it hard to quickly find the method that is relevant to what you are looking for.

![Screenshot 2020-01-21 at 11 22 16](https://user-images.githubusercontent.com/249719/72796832-50d60c00-3c40-11ea-8b92-d749283c6b71.png)

## Expected Behavior
I would expect better categories for the different areas. Such as Analytics, Build, Crashes, Login etc.

## Current Behavior
Everything is in the same "General" category

## Possible Solution
Provide different `CakeAliasCategoryAttribute` for different categories of methods.

**Comment by MihaMarkic** [comment]
That's auto generated. Do you have a suggestion what should be a category? Top level command perhaps?

**Comment by Cheesebaron** [comment]
@MihaMarkic yeah, I think that would be much nicer with top level command being the category.
