### ISSUE TITLE
Add ability to upload to a store

### ISSUE THREAD

**Issue by steverichey** [cake-contrib/Cake.AppCenter#18]
## Expected Behavior
The following App Center CLI commands have no equivalent for Cake:

    appcenter distribute stores list
    appcenter distribute stores publish

## Current Behavior
Currently this is not possible.

## Possible Solution
Add the following aliases:

    AppCenterDistributeStoresList
    AppCenterDistributeStoresListWithResult
    AppCenterDistributeStoresPublish
    AppCenterDistributeStoresPublishWithResult

## Context
Currently attempting to use Cake for the full CI/deploy pipeline, and this is a missing integration.

**Comment by MihaMarkic** [comment]
Hi @steverichey 

First, thanks for creating a PR. However, the code is mostly autogenerated and I just updated it for for CLI v2.7.3 in #20. Can you give it a quick test. I'm planning to release it soon.

**Comment by steverichey** [comment]
@MihaMarkic I'm not sure how one would do a store release with the new changes; I see `AppCenterDistributeStoresList` but not `AppCenterDistributeStoresPublish`.

**Comment by steverichey** [comment]
You may need to update the gitignore file; I had to change `publish/` to `./publish/` in my merge request, in order to pick up the `src/Cake.AppCenter/Distribute/Releases/Stores/Publish` folder.

**Comment by MihaMarkic** [comment]
Good catch, it might very well be the case

**Comment by MihaMarkic** [comment]
Fixed in e770d9931e1fa812a96f6eb7fa9d76bc17cc4bc1 by simply removing publish which was set as Click Once ignored directory. Thanks.

**Comment by steverichey** [comment]
The new aliases look good to me. Thanks!
