### ISSUE TITLE
Update Cake.Core to 2.0.0

### ISSUE THREAD

**Issue by rojasjo** [cake-contrib/Cake.AppCenter#28]
When distributing there are warning because Cake.AppCenter is referencing older versions of Cake.Core

## Expected Behavior
When distributing no warnings are shown.

## Current Behavior
When distributing the following warning is shown:
The assembly 'Cake.AppCenter, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (1.0.0).
For best compatibility it should target Cake.Core version 2.0.0.

Thank you very much for this library, awesome job!

**Comment by MihaMarkic** [comment]
Will update to 4.0.0 instead

**Comment by MihaMarkic** [comment]
Grega vzame resno in ob 15:15 potrdi odpoveda

**Comment by MihaMarkic** [comment]
Will update to 4.0.0 instead
